package com.ed.twitterdownloader.ui.theme

import androidx.compose.ui.graphics.Color

// Apple-style palette
val md_primary = Color(0xFF0071E3)
val md_onPrimary = Color(0xFFFFFFFF)
val md_primaryContainer = Color(0xFFE3F0FF)
val md_onPrimaryContainer = Color(0xFF004A9F)
val md_secondary = Color(0xFF5856D6)
val md_onSecondary = Color(0xFFFFFFFF)
val md_secondaryContainer = Color(0xFFE5E4FF)
val md_onSecondaryContainer = Color(0xFF1D1A8D)
val md_tertiary = Color(0xFF34C759)
val md_onTertiary = Color(0xFFFFFFFF)
val md_tertiaryContainer = Color(0xFFD7F5E3)
val md_onTertiaryContainer = Color(0xFF0A5E2A)
val md_error = Color(0xFFFF3B30)
val md_onError = Color(0xFFFFFFFF)
val md_errorContainer = Color(0xFFFFDAD6)
val md_onErrorContainer = Color(0xFF93000A)
val md_background = Color(0xFFF5F5F7)
val md_onBackground = Color(0xFF1D1D1F)
val md_surface = Color(0xFFFFFFFF)
val md_onSurface = Color(0xFF1D1D1F)
val md_surfaceVariant = Color(0xFFE8E8ED)
val md_onSurfaceVariant = Color(0xFF6E6E73)
val md_outline = Color(0xFFD2D2D7)
val md_outlineVariant = Color(0xFFE8E8ED)
val md_surfaceContainerLow = Color(0xFFFAFAFC)
val md_surfaceContainer = Color(0xFFF5F5F7)
val md_surfaceContainerHigh = Color(0xFFEEEEF2)
val md_surfaceContainerHighest = Color(0xFFE8E8ED)

// Dark
val md_primary_dark = Color(0xFF6EB4FF)
val md_onPrimary_dark = Color(0xFF003A7A)
val md_primaryContainer_dark = Color(0xFF0055B0)
val md_onPrimaryContainer_dark = Color(0xFFD4E4FF)
val md_secondary_dark = Color(0xFFC2C0FF)
val md_onSecondary_dark = Color(0xFF2722A8)
val md_secondaryContainer_dark = Color(0xFF3E3ABE)
val md_onSecondaryContainer_dark = Color(0xFFE5E4FF)
val md_tertiary_dark = Color(0xFF5EE88A)
val md_onTertiary_dark = Color(0xFF003916)
val md_tertiaryContainer_dark = Color(0xFF005223)
val md_onTertiaryContainer_dark = Color(0xFFD7F5E3)
val md_error_dark = Color(0xFFFFB4AB)
val md_onError_dark = Color(0xFF690005)
val md_errorContainer_dark = Color(0xFF93000A)
val md_onErrorContainer_dark = Color(0xFFFFDAD6)
val md_background_dark = Color(0xFF1C1C1E)
val md_onBackground_dark = Color(0xFFE5E5EA)
val md_surface_dark = Color(0xFF2C2C2E)
val md_onSurface_dark = Color(0xFFE5E5EA)
val md_surfaceVariant_dark = Color(0xFF3A3A3C)
val md_onSurfaceVariant_dark = Color(0xFFC6C6C8)
val md_outline_dark = Color(0xFF48484A)
val md_outlineVariant_dark = Color(0xFF3A3A3C)
val md_surfaceContainerLow_dark = Color(0xFF262628)
val md_surfaceContainer_dark = Color(0xFF323234)
val md_surfaceContainerHigh_dark = Color(0xFF3D3D3F)
val md_surfaceContainerHighest_dark = Color(0xFF48484A)

